[data]
location = "./sample/nf4_clover_wilson_finiteT"
ensemble = "L12T4b1.60k13575"
analysis_header = "analysis"
TrM1_X = ["plaq.dat","rect.dat"]
TrM1_Y = "pbp.dat"
TrM1_model = "LightGBM"
TrM1_read_column_X = [1,1]
TrM1_read_column_Y = 1
TrM1_index_column = 3
TrM2_X = ["plaq.dat","rect.dat"]
TrM2_Y = "trdinv2.dat"
TrM2_model = "LightGBM"
TrM2_read_column_X = [1,1]
TrM2_read_column_Y = 1
TrM2_index_column = 3
TrM3_X = ["plaq.dat","rect.dat"]
TrM3_Y = "trdinv3.dat"
TrM3_model = "LightGBM"
TrM3_read_column_X = [1,1]
TrM3_read_column_Y = 1
TrM3_index_column = 3
TrM4_X = ["plaq.dat","rect.dat"]
TrM4_Y = "trdinv4.dat"
TrM4_model = "LightGBM"
TrM4_read_column_X = [1,1]
TrM4_read_column_Y = 1
TrM4_index_column = 3
LBP = 30
TRP = 30
use_abbreviation = true

[input_meta]
ns = 12
nt = 4
nf = 4
beta = 1.60
kappa = 0.13575

[bootstrap]
ranseed = 850528
N_bs = 1000
blk_size = 1
method = "nonoverlapping"

[jackknife]
bin_size = 1

[deborah]
IDX_shift = 0
dump_X = false

[abbreviation]
"pbp.dat"     = "TrM1"
"trdinv2.dat" = "TrM2"
"trdinv3.dat" = "TrM3"
"trdinv4.dat" = "TrM4"
"plaq.dat"    = "Plaq"
"ploop.dat"   = "Loop"
"rect.dat"    = "Rect"