[data]
labels = ["5","10","15","20","25","30","35","40","45","50"]
trains = ["10","20","30","40","50","60","70","80","90"]
location = "./sample/nf4_clover_wilson_finiteT"
ensemble = "L12T4b1.60k13575"
analysis_header = "analysis"
X = ["plaq.dat","rect.dat"]
Y = "pbp.dat"
model = "LightGBM"
read_column_X = [1,1]
read_column_Y = 1
index_column = 3
IDX_shift = 0
dump_X = false
use_abbreviation = true

[bootstrap]
ranseed = 850528
N_bs = 1000
blk_size = 1
method = "nonoverlapping"

[jackknife]
bin_size = 1

[abbreviation]
"pbp.dat" = "TrM1"
"trdinv2.dat" = "TrM2"
"trdinv3.dat" = "TrM3"
"trdinv4.dat" = "TrM4"
"plaq.dat" = "Plaq"
"ploop.dat" = "Loop"
"rect.dat" = "Rect"