[data]
labels = ["5","10","15","20","25","30","35","40","45","50"]
trains = ["0","10","20","30","40","50","60","70","80","90","100"]
location = "./nf4_clover_wilson_finiteT"
multi_ensemble = "L12T4b1.60"
ensembles = ["L12T4b1.60k13575","L12T4b1.60k13577","L12T4b1.60k13580","L12T4b1.60k13582","L12T4b1.60k13585"]
analysis_header = "analysis"
TrM1_X = ["plaq.dat","rect.dat"]
TrM1_Y = "pbp.dat"
TrM1_model = "LightGBM"
TrM1_read_column_X = [1,1]
TrM1_read_column_Y = 1
TrM1_index_column = 3
TrM2_X = ["plaq.dat","rect.dat"]
TrM2_Y = "trdinv2.dat"
TrM2_model = "LightGBM"
TrM2_read_column_X = [1,1]
TrM2_read_column_Y = 1
TrM2_index_column = 3
TrM3_X = ["plaq.dat","rect.dat"]
TrM3_Y = "trdinv3.dat"
TrM3_model = "LightGBM"
TrM3_read_column_X = [1,1]
TrM3_read_column_Y = 1
TrM3_index_column = 3
TrM4_X = ["plaq.dat","rect.dat"]
TrM4_Y = "trdinv4.dat"
TrM4_model = "LightGBM"
TrM4_read_column_X = [1,1]
TrM4_read_column_Y = 1
TrM4_index_column = 3
dump_original = false
use_abbreviation = true

[input_meta]
ns = 12
nt = 4
nf = 4
beta = 1.60
csw = 2.065
kappa_list = [0.13575,0.13577,0.13580,0.13582,0.13585]

[solver]
maxiter = 1000
eps = 1e-13

[jackknife]
bin_size = 400

[bootstrap]
ranseed = 850528
N_bs = 1000
blk_size = 400
method = "nonoverlapping"

[trajectory]
nkappaT = 100

[deborah]
IDX_shift = 0
dump_X = false

[abbreviation]
"pbp.dat" = "TrM1"
"trdinv2.dat" = "TrM2"
"trdinv3.dat" = "TrM3"
"trdinv4.dat" = "TrM4"
"plaq.dat" = "Plaq"
"ploop.dat" = "Loop"
"rect.dat" = "Rect"
