name: Build and deploy Deborah.jl docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Install dependencies
        run: |
          julia --project=doc -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();
          '

      - name: Build and deploy docs
        run: julia --project=doc doc/make.jl